version: '3'
services:

  refuapp-backend:
    ports:
      - "8000:8000"

  refuapp-frontend:
    build:
      args:
        - BACKEND_URL=http://localhost:8000
    ports:
      - '80:80'

  refuapp-admin-frontend:
    build:
      args:
        - BACKEND_URL=http://localhost:8000
    ports:
      - '81:80'
