version: '3'
services:

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${BACKEND_DB_NAME}
      POSTGRES_USER: ${BACKEND_DB_USER}
      POSTGRES_PASSWORD: ${BACKEND_DB_PASSWORD}

  refuapp-backend:
    build:
      context: ./refuapp-backend  # Path to your project directory
      dockerfile: Dockerfile
    external_links:
      - postgres:docker-mysql
    environment:
      DB_NAME: ${BACKEND_DB_NAME}
      DB_USER: ${BACKEND_DB_USER}
      DB_PASSWORD: ${BACKEND_DB_PASSWORD}
      DB_PORT: ${BACKEND_DB_PORT}
      DB_HOST: docker-mysql
      JWT_KEY: ${BACKEND_JWT_KEY}
    depends_on:
      - postgres
    ports:
      - "8000:8000"

  refuapp-frontend:
    build:
      context: ./refuapp-frontend  # Path to your project directory
      dockerfile: Dockerfile
      args:
        - MAPS_API_KEY=${FRONTEND_MAPS_API_KEY}
        - BACKEND_URL=http://localhost:8000
    depends_on:
      - refuapp-backend
    ports:
      - '80:80'

  refuapp-admin-frontend:
    build:
      context: ./refuapp-admin
      dockerfile: Dockerfile
      args:
        - BACKEND_URL=http://localhost:8000
    depends_on:
      - refuapp-backend
    ports:
      - '81:80'

  sensors_db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${SENSORS_DB_NAME}
      POSTGRES_USER: ${SENSORS_DB_USER}
      POSTGRES_PASSWORD: ${SENSORS_DB_PASS}

  refuapp-sensor-backend:
    build:
      context: ./refuge-sensor-server/
      dockerfile: Dockerfile
    external_links:
      - sensors_db:docker-mysql
    environment:
      DB_NAME: ${SENSORS_DB_NAME}
      DB_USER: ${SENSORS_DB_USER}
      DB_PASS: ${SENSORS_DB_PASS}
      DB_HOST: docker-mysql
      DB_PORT: ${SENSORS_DB_PORT}
    depends_on:
      - sensors_db
