version: '3'
services:

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${BACKEND_DB_NAME}
      POSTGRES_USER: ${BACKEND_DB_USER}
      POSTGRES_PASSWORD: ${BACKEND_DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  refuapp-backend:
    build:
      context: ./refuapp-backend  # Path to your project directory
      dockerfile: Dockerfile
    external_links:
      - postgres:docker-mysql
    environment:
      DB_NAME: ${BACKEND_DB_NAME}
      DB_USER: ${BACKEND_DB_USER}
      DB_PASSWORD: ${BACKEND_DB_PASSWORD}
      DB_PORT: ${BACKEND_DB_PORT}
      DB_HOST: docker-mysql
      JWT_KEY: ${BACKEND_JWT_KEY}
    depends_on:
      - postgres

  refuapp-frontend:
    build:
      context: ./refuapp-frontend  # Path to your project directory
      dockerfile: Dockerfile
      args:
        - MAPS_API_KEY=${FRONTEND_MAPS_API_KEY}
    depends_on:
      - refuapp-backend

  nginxproxymanager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginxproxymanager
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./proxy-manager/data:/data
      - ./proxy-manager/letsencrypt:/etc/letsencrypt

  sensors_db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${SENSORS_DB_NAME}
      POSTGRES_USER: ${SENSORS_DB_USER}
      POSTGRES_PASSWORD: ${SENSORS_DB_PASS}
    volumes:
      - postgres_sensor_data:/var/lib/postgresql/data

  refuapp-sensor-backend:
    build:
      context: ./refuge-sensor-server/
      dockerfile: Dockerfile
    external_links:
      - sensors_db:docker-mysql
    environment:
      DB_NAME: ${SENSORS_DB_NAME}
      DB_USER: ${SENSORS_DB_USER}
      DB_PASS: ${SENSORS_DB_PASS}
      DB_HOST: docker-mysql
      DB_PORT: ${SENSORS_DB_PORT}
    depends_on:
      - sensors_db

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      device: /home/ferran/data
      o: bind
  postgres_sensor_data:
    driver: local
    driver_opts:
      type: none
      device: /home/ferran/data-sensors
      o: bind
