version: '3'
services:

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: refuapp
      POSTGRES_USER: refuapp_user
      POSTGRES_PASSWORD: refuapp_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  refuapp-backend:
    build:
      context: ./refuapp-backend  # Path to your project directory
      dockerfile: Dockerfile
    external_links:
      - postgres:docker-mysql
    environment:
      DATABASE_URL: postgresql+psycopg2://refuapp_user:refuapp_password@docker-mysql:5432/refuapp
    depends_on:
      - postgres

  refuapp-frontend:
    build:
      context: ./refuapp-frontend  # Path to your project directory
      dockerfile: Dockerfile
    depends_on:
      - refuapp-backend
    environment:
      MAPS_API_KEY: ${MAPS_API_KEY}

  nginxproxymanager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginxproxymanager
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./proxy-manager/data:/data
      - ./proxy-manager/letsencrypt:/etc/letsencrypt

  sensors_db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - postgres_sensor_data:/var/lib/postgresql/data

  refuapp-sensor-backend:
    build:
      context: ./refuge-sensor-server/
      dockerfile: Dockerfile
    external_links:
      - sensors_db:docker-mysql
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: docker-mysql
      DB_PORT: 5432
    depends_on:
      - sensors_db

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      device: /home/ferran/data
      o: bind
  postgres_sensor_data:
    driver: local
    driver_opts:
      type: none
      device: /home/ferran/data-sensors
      o: bind
