version: '3'
services:

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: refuapp
      POSTGRES_USER: refuapp_user
      POSTGRES_PASSWORD: refuapp_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks: 
      - backend

  refuapp-backend:
    build:
      context: ./refuapp-backend  # Path to your project directory
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    external_links:
      - postgres:docker-mysql
    environment:
      DATABASE_URL: postgresql+psycopg2://refuapp_user:refuapp_password@docker-mysql:5432/refuapp
    depends_on:
      - postgres
    networks: 
      - backend

  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - URL=api.pofnet.net
      - VALIDATION=http
      - EMAIL=pablofrailealonso@gmail.com
      - PROD=true
    volumes:
      - /home/ferran/refuapp-deploy/nginx/site-confs:/config/nginx/site-confs
      - /home/ferran/www/:/var/www
      - /home/ferran/static/:/static
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
    depends_on:
      - refuapp-backend
    networks:
      - backend


networks:
  backend:
    driver: "bridge"

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      device: /home/ferran/data
      o: bind
  frontend_page:
    driver: local
    driver_opts:
      type: none
      device: /home/ferran/web
  static_files:
    driver: local
    driver_opts:
      type: none
      device: /home/ferran/static
  swag_config_files:
    driver: local
    driver_opts:
      type: none
      device: /home/ferran/refuapp-deploy
